# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dy2018_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('hash', models.CharField(blank=True, max_length=300, null=True)),
                ('include_date', models.DateField()),
            ],
            options={
                'ordering': ('-include_date',),
            },
        ),
        migrations.CreateModel(
            name='dy2018_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
