# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house_retal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('estate', models.CharField(max_length=300)),
                ('house_type', models.CharField(max_length=300)),
                ('acreage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('source', models.CharField(max_length=300)),
                ('include_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-include_date',),
            },
        ),
    ]
